# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "15 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: stecrotti1
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Rome
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_charts: yes 
          plugin_habits_trim: yes       
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: PLpgSQL
          plugin_languages_colors: github
          plugin_languages_limit: 0
          plugin_languages_recent.days: 14
          plugin_languages_recent.load: 300
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage 
          plugin_languages_threshold: 0%
          plugin_activity: yes
          plugin_activity_limit: 5           # Limit to 5 events
          plugin_activity_load: 100          # Load up to 100 recent events from API (should be higher than "limit")
          plugin_activity_days: 14           # Keep only events from last 14 days (set to 0 for no limit)
          plugin_activity_filter: all        # Show all events (use table above to filter events types)
          plugin_activity_visibility: public # Only display public events
          plugin_activity_timestamps: yes    # Display events timestamps
          plugin_activity_skipped: repo      # Ignored repositories
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_topics_sort: stars
