# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "15 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: stecrotti1
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Rome     
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: PLpgSQL
          plugin_languages_colors: github
          plugin_languages_limit: 0
          plugin_languages_recent.days: 14
          plugin_languages_recent.load: 300
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage 
          plugin_languages_threshold: 0%
          plugin_activity: yes
          plugin_activity_limit: 5           
          plugin_activity_load: 100          
          plugin_activity_days: 14           
          plugin_activity_filter: all        
          plugin_activity_visibility: public 
          plugin_activity_timestamps: yes    
          plugin_activity_skipped: repo      
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_topics_sort: stars
